using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Glimpse for EF (Alpha)")]
[assembly: AssemblyDescription("EntityFramework plugin for Glimpse. This package adds a tab displaying SQL activity generated by EF 4.0 or EF 4.1. EF 4.1 Update and EF 4.2 CTP are not supported at this time. (Alpha)")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("nmolnar, avanderhoorn")]
[assembly: AssemblyProduct("Glimpse.Ef")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("61266d72-5987-460b-9536-eb164c9e0b4b")]

[assembly: AssemblyVersion("0.0.5")]
[assembly: AssemblyFileVersion("0.0.5")]
