//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glimpse.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glimpse.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods inspected via proxy generation hook on type &apos;{0}&apos;..
        /// </summary>
        internal static string AlternateTypeGenerationHookMethodsInspected {
            get {
                return ResourceManager.GetString("AlternateTypeGenerationHookMethodsInspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} method of type &apos;{1}&apos; is not proxyable..
        /// </summary>
        internal static string AlternateTypeGenerationHookNonProxyableMemberNotification {
            get {
                return ResourceManager.GetString("AlternateTypeGenerationHookNonProxyableMemberNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize method has not been called in the context on the current Glimpse runtime instance. Calls to BeginRequest must be preceded by calls to Initialize..
        /// </summary>
        internal static string BeginRequestOutOfOrderRuntimeMethodCall {
            get {
                return ResourceManager.GetString("BeginRequestOutOfOrderRuntimeMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} of type &apos;{1}&apos; to collection..
        /// </summary>
        internal static string DiscoverableCollectionAddItem {
            get {
                return ResourceManager.GetString("DiscoverableCollectionAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared {0} collection..
        /// </summary>
        internal static string DiscoverableCollectionClearItems {
            get {
                return ResourceManager.GetString("DiscoverableCollectionClearItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} of type &apos;{1}&apos; from collection..
        /// </summary>
        internal static string DiscoverableCollectionRemoveItem {
            get {
                return ResourceManager.GetString("DiscoverableCollectionRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception loading &apos;{0}&apos; of type &apos;{1}&apos;..
        /// </summary>
        internal static string DiscoverCreateInstance {
            get {
                return ResourceManager.GetString("DiscoverCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load type when getting types from assembly &apos;{0}&apos;.
        /// </summary>
        internal static string DiscoverGetType {
            get {
                return ResourceManager.GetString("DiscoverGetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception loading assembly at path &apos;{0}&apos;..
        /// </summary>
        internal static string DiscoverLoadAssembly {
            get {
                return ResourceManager.GetString("DiscoverLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance extension of type &apos;{0}&apos; failed to execute..
        /// </summary>
        internal static string ExecuteInstanceMetadataExtensionsError {
            get {
                return ResourceManager.GetString("ExecuteInstanceMetadataExtensionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension of type &apos;{0}&apos; failed to execute..
        /// </summary>
        internal static string ExecuteMetadataExtensionsError {
            get {
                return ResourceManager.GetString("ExecuteMetadataExtensionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception executing policy of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExecutePolicyWarning {
            get {
                return ResourceManager.GetString("ExecutePolicyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous resource with name &apos;{0}&apos; found..
        /// </summary>
        internal static string ExecuteResourceDuplicateError {
            get {
                return ResourceManager.GetString("ExecuteResourceDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime policy does not allow execution of resource named &apos;{0}&apos;..
        /// </summary>
        internal static string ExecuteResourceInsufficientPolicy {
            get {
                return ResourceManager.GetString("ExecuteResourceInsufficientPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource with name &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string ExecuteResourceMissingError {
            get {
                return ResourceManager.GetString("ExecuteResourceMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception executing tab of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExecuteTabError {
            get {
                return ResourceManager.GetString("ExecuteTabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension tab of type &apos;{0}&apos; failed to execute..
        /// </summary>
        internal static string ExecuteTabMetadataExtensionsError {
            get {
                return ResourceManager.GetString("ExecuteTabMetadataExtensionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception generating script tag for dynamic IClientScript of type &apos;{0}&apos;..
        /// </summary>
        internal static string GenerateScriptTagsDynamicException {
            get {
                return ResourceManager.GetString("GenerateScriptTagsDynamicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception generating script tag for static IClientScript of type &apos;{0}&apos;..
        /// </summary>
        internal static string GenerateScriptTagsStaticException {
            get {
                return ResourceManager.GetString("GenerateScriptTagsStaticException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception generating uri with ResourceEndpointConfiguration of type &apos;{0}&apos;..
        /// </summary>
        internal static string GenerateUriExecutionError {
            get {
                return ResourceManager.GetString("GenerateUriExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception getting Parameters for IResource of type &apos;{0}&apos;..
        /// </summary>
        internal static string GenerateUriParameterKeysWarning {
            get {
                return ResourceManager.GetString("GenerateUriParameterKeysWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not persist metadata with IPersistenceStore of type &apos;{0}&apos;..
        /// </summary>
        internal static string GlimpseRuntimeEndRequesPersistError {
            get {
                return ResourceManager.GetString("GlimpseRuntimeEndRequesPersistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing IResource &apos;{0}&apos;..
        /// </summary>
        internal static string GlimpseRuntimeExecuteResourceError {
            get {
                return ResourceManager.GetString("GlimpseRuntimeExecuteResourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing resource result of type &apos;{0}&apos;..
        /// </summary>
        internal static string GlimpseRuntimeExecuteResourceResultError {
            get {
                return ResourceManager.GetString("GlimpseRuntimeExecuteResourceResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup IInspector of type &apos;{0}&apos;..
        /// </summary>
        internal static string GlimpseRuntimeInitializeSetupInspector {
            get {
                return ResourceManager.GetString("GlimpseRuntimeInitializeSetupInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Resources with name of &apos;{0}&apos;. Resources should have unique names..
        /// </summary>
        internal static string GlimpseRuntimePersistMetadataMultipleResourceWarning {
            get {
                return ResourceManager.GetString("GlimpseRuntimePersistMetadataMultipleResourceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception initializing inspector of type &apos;{0}&apos;..
        /// </summary>
        internal static string InitializeInspectorError {
            get {
                return ResourceManager.GetString("InitializeInspectorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception initializing tab of type &apos;{0}&apos;..
        /// </summary>
        internal static string InitializeTabError {
            get {
                return ResourceManager.GetString("InitializeTabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to instantiate Framework Provider from IServiceLocator: &apos;{0}&apos; or &apos;{1}&apos;..
        /// </summary>
        internal static string InstantiateFrameworkProviderException {
            get {
                return ResourceManager.GetString("InstantiateFrameworkProviderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to instantiate Resource Endpoint Configuration from IServiceLocator: &apos;{0}&apos; or &apos;{1}&apos;..
        /// </summary>
        internal static string InstantiateResourceEndpointConfigurationException {
            get {
                return ResourceManager.GetString("InstantiateResourceEndpointConfigurationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; on type &apos;{1}&apos; has been subscribed to all &apos;{2}&apos; messages..
        /// </summary>
        internal static string MessageBrokerSubscribe {
            get {
                return ResourceManager.GetString("MessageBrokerSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid privileged resource execution on &apos;{0}&apos;. Call overload Execute(IResourceContext, IGlimpseConfiguration) instead..
        /// </summary>
        internal static string PrivilegedResourceExecuteNotSupported {
            get {
                return ResourceManager.GetString("PrivilegedResourceExecuteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to render IClientScript: &apos;{0}&apos;. All IClientScript implementations should also implement either IStaticClientScript or IDynamicClientScript..
        /// </summary>
        internal static string RenderClientScriptImproperImplementationWarning {
            get {
                return ResourceManager.GetString("RenderClientScriptImproperImplementationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to render IClientScript: &apos;{0}&apos;. No IResource with the Name &apos;{1}&apos; could be found..
        /// </summary>
        internal static string RenderClientScriptMissingResourceWarning {
            get {
                return ResourceManager.GetString("RenderClientScriptMissingResourceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value &apos;{0}&apos; creates path &apos;{1}&apos;, which does not exist..
        /// </summary>
        internal static string SetDiscoveryLocationDirectoryNotFoundMessage {
            get {
                return ResourceManager.GetString("SetDiscoveryLocationDirectoryNotFoundMessage", resourceCulture);
            }
        }
    }
}
