namespace Glimpse.Core.Extensibility
{
    public interface IDynamicClientScript : IClientScript
    {
        /// <summary>
        /// Gets the name of the corresponding IResource. 
        /// </summary>
        /// <remarks>
        /// IDynamicClientScript's render a script tag with a source URL pointing to an IResource that is configured in Glimpse. IResource URL's are generated by the ResourceEndpointConfiguration instance.
        /// </remarks>
        /// <returns><see cref="string"/></returns>
        string GetResourceName();
    }
}