namespace Glimpse.Core.Extensibility
{
    /// <summary>
    /// The <c>ScriptOrder</c> enumeration specifies the sorting order placement of <c>&lt;script&gt;</c> tags generated by <see cref="IClientScript"/>'s within a page response.
    /// </summary>
    public enum ScriptOrder
    {
        /// <summary>
        /// The first <c>&lt;script&gt;</c> tags rendered. The Glimpse client has not yet been rendered, as such <see cref="IClientScript"/>'s with this <see cref="ScriptOrder"/> should only perform setup tasks.
        /// </summary>
        IncludeBeforeClientInterfaceScript,
        
        /// <summary>
        /// The <c>&lt;script&gt;</c> tags representing the main Glimpse client.
        /// </summary>
        /// <remarks>
        /// This value is typically only used by Glimpse itself to render the main Glimpse JavaScript client.
        /// </remarks>
        ClientInterfaceScript,
        
        /// <summary>
        /// The <c>&lt;script&gt;</c> tags rendered immediately after the Glimpse client. These scripts usually customize or extend the Glimpse client.
        /// </summary>
        IncludeAfterClientInterfaceScript,
        
        /// <summary>
        /// The <c>&lt;script&gt;</c> tags representing a resource to obtain Glimpse's server side configuration metadata.
        /// </summary>
        /// <remarks>
        /// This value is typically only used by Glimpse server implementers.
        /// </remarks>
        RequestMetadataScript,
        
        /// <summary>
        /// The <c>&lt;script&gt;</c> tags rendered after Glimpse's server side configuration metadata. These scripts usually append or alter the server side metadata before the client has actually rendered.
        /// </summary>
        IncludeBeforeRequestDataScript,
        
        /// <summary>
        /// The <c>&lt;script&gt;</c> tags representing a resource to all metadata gathered for the given Http request.
        /// </summary>
        /// <remarks>
        /// This value is typically only used by Glimpse server implementers.
        /// </remarks>
        RequestDataScript,
        
        /// <summary>
        /// The last <c>&lt;script&gt;</c> tags rendered. These scripts usually append or alter Http request data.
        /// </summary>
        IncludeAfterRequestDataScript,
    }
}