using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Glimpse for ADO (Beta)")]
[assembly: AssemblyDescription("ADO plugin for Glimpse. This package adds a tab displaying SQL activity generated by ADO.NET providers that are created through a DbProviderFactory.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("nmolnar, avanderhoorn")]
[assembly: AssemblyProduct("Glimpse.Ado")]
[assembly: AssemblyCopyright("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("f2d6bd18-342c-4ae1-a63a-252265c5c16d")]

[assembly: AssemblyVersion("0.87")]
[assembly: AssemblyFileVersion("0.87")]