//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glimpse.AspNet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glimpse.AspNet.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already processed event &apos;{0}&apos; of &apos;{1}&apos; (#{2}), therefore bypassing the event handling.
        /// </summary>
        internal static string GlimpseRuntimeWrapperAlreadyHandledEvent {
            get {
                return ResourceManager.GetString("GlimpseRuntimeWrapperAlreadyHandledEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glimpse.AspNet.GlimpseRuntimeWrapper : Executing default resource.
        /// </summary>
        internal static string GlimpseRuntimeWrapperExecuteDefaultResource {
            get {
                return ResourceManager.GetString("GlimpseRuntimeWrapperExecuteDefaultResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing resource &apos;{0}&apos;.
        /// </summary>
        internal static string GlimpseRuntimeWrapperExecuteResource {
            get {
                return ResourceManager.GetString("GlimpseRuntimeWrapperExecuteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling event &apos;{0}&apos; of &apos;{1}&apos; (#{2}).
        /// </summary>
        internal static string GlimpseRuntimeWrapperHandlingEvent {
            get {
                return ResourceManager.GetString("GlimpseRuntimeWrapperHandlingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glimpse.AspNet.HttpModule : Init called on &apos;{0}&apos; (#{1}) for &apos;{2}&apos; (#{3}).
        /// </summary>
        internal static string HttpModuleInitIsCalled {
            get {
                return ResourceManager.GetString("HttpModuleInitIsCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glimpse.AspNet.HttpModule : &apos;{0}&apos; instantiated and added to &apos;{1}&apos; (#{2}).
        /// </summary>
        internal static string HttpModuleInstantiatedGlimpseRuntimeWrapper {
            get {
                return ResourceManager.GetString("HttpModuleInstantiatedGlimpseRuntimeWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glimpse runtime has not been initialized..
        /// </summary>
        internal static string ProcessRequestMissingRuntime {
            get {
                return ResourceManager.GetString("ProcessRequestMissingRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t replace route of type &apos;{0}&apos; with proxy implementation..
        /// </summary>
        internal static string RouteSetupNotReplacedRoute {
            get {
                return ResourceManager.GetString("RouteSetupNotReplacedRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced Route of type &apos;{0}&apos; with proxy implementation..
        /// </summary>
        internal static string RouteSetupReplacedRoute {
            get {
                return ResourceManager.GetString("RouteSetupReplacedRoute", resourceCulture);
            }
        }
    }
}
