//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glimpse.Core2.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glimpse.Core2.Resource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception executing tab: {0}.
        /// </summary>
        internal static string ExecutePluginError {
            get {
                return ResourceManager.GetString("ExecutePluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception initializing pipeline inspector: {0}.
        /// </summary>
        internal static string InitializePipelineInspectorError {
            get {
                return ResourceManager.GetString("InitializePipelineInspectorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception initializing tab: {0}.
        /// </summary>
        internal static string InitializeTabError {
            get {
                return ResourceManager.GetString("InitializeTabError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeginRequest has not been called in the context of the current HTTP request. Calls to EndRequest must be preceded by calls to BeginRequest..
        /// </summary>
        internal static string OutOfOrderRuntimeMethodCall {
            get {
                return ResourceManager.GetString("OutOfOrderRuntimeMethodCall", resourceCulture);
            }
        }
    }
}
