//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glimpse.Mvc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glimpse.Mvc.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxied IControllerFactory of type &apos;{0}&apos;..
        /// </summary>
        internal static string ControllerFactorySetup {
            get {
                return ResourceManager.GetString("ControllerFactorySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t replace IDependencyResolver of type &apos;{0}&apos; with proxy implementation..
        /// </summary>
        internal static string DependencyResolverSetupNotReplacedDependencyResolver {
            get {
                return ResourceManager.GetString("DependencyResolverSetupNotReplacedDependencyResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced IDependencyResolver of type &apos;{0}&apos; with proxy implementation..
        /// </summary>
        internal static string DependencyResolverSetupReplacedDependencyResolver {
            get {
                return ResourceManager.GetString("DependencyResolverSetupReplacedDependencyResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced IView of type &apos;{0}&apos;, named &apos;{1}&apos;, with proxy implementation..
        /// </summary>
        internal static string FindViewsProxyOutputReplacedIView {
            get {
                return ResourceManager.GetString("FindViewsProxyOutputReplacedIView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot proxy model binder of type &apos;{0}&apos; because it is not a System.Web.Mvc.DefaultModelBinder..
        /// </summary>
        internal static string GetBinderNewImplementationCannotProxyWarning {
            get {
                return ResourceManager.GetString("GetBinderNewImplementationCannotProxyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced IModelBinder of type &apos;{0}&apos; with proxy implementation..
        /// </summary>
        internal static string ModelBinderInspectorSetupReplacedModelBinder {
            get {
                return ResourceManager.GetString("ModelBinderInspectorSetupReplacedModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced IModelBinderProvider of type &apos;{0}&apos; with proxy implementation..
        /// </summary>
        internal static string ModelBinderInspectorSetupReplacedModelBinderProvider {
            get {
                return ResourceManager.GetString("ModelBinderInspectorSetupReplacedModelBinderProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced ValueProviderFactory of type &apos;{0}&apos; with proxy implementation..
        /// </summary>
        internal static string ModelBinderInspectorSetupReplacedValueProviderFactory {
            get {
                return ResourceManager.GetString("ModelBinderInspectorSetupReplacedValueProviderFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t replace IViewEngine of type &apos;{0}&apos; with proxy implementation..
        /// </summary>
        internal static string ViewEngineSetupNotReplacedViewEngine {
            get {
                return ResourceManager.GetString("ViewEngineSetupNotReplacedViewEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced IViewEngine of type &apos;{0}&apos; with proxy implementation..
        /// </summary>
        internal static string ViewEngineSetupReplacedViewEngine {
            get {
                return ResourceManager.GetString("ViewEngineSetupReplacedViewEngine", resourceCulture);
            }
        }
    }
}
