// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Glimpse.Site.Controllers {
    public partial class AboutController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AboutController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AboutController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AboutController Actions { get { return MVC.About; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "About";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string Details = "Details";
            public readonly string Credits = "Credits";
            public readonly string Platforms = "Platforms";
            public readonly string Roadmap = "Roadmap";
            public readonly string QuickStart = "QuickStart";
            public readonly string Features = "Features";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Credits = "~/Views/About/Credits.cshtml";
            public readonly string Details = "~/Views/About/Details.cshtml";
            public readonly string Features = "~/Views/About/Features.cshtml";
            public readonly string Index = "~/Views/About/Index.cshtml";
            public readonly string Platforms = "~/Views/About/Platforms.cshtml";
            public readonly string QuickStart = "~/Views/About/QuickStart.cshtml";
            public readonly string Roadmap = "~/Views/About/Roadmap.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AboutController: Glimpse.Site.Controllers.AboutController {
        public T4MVC_AboutController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Details() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Details);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Credits() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Credits);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Platforms() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Platforms);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Roadmap() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Roadmap);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult QuickStart() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.QuickStart);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Features() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Features);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
