// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace MvcMusicStore.Controllers {
    public partial class CheckoutController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CheckoutController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CheckoutController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Complete() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.Complete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CheckoutController Actions { get { return MVC.Checkout; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Checkout";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string AddressAndPayment = "AddressAndPayment";
            public readonly string Complete = "Complete";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string AddressAndPayment = "~/Views/Checkout/AddressAndPayment.cshtml";
            public readonly string Complete = "~/Views/Checkout/Complete.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_CheckoutController: MvcMusicStore.Controllers.CheckoutController {
        public T4MVC_CheckoutController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult AddressAndPayment() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddressAndPayment);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AddressAndPayment(System.Web.Mvc.FormCollection values) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AddressAndPayment);
            callInfo.RouteValueDictionary.Add("values", values);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Complete(int id) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Complete);
            callInfo.RouteValueDictionary.Add("id", id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
